version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
    command: "yarn start -H 0.0.0.0"
    environment:
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - VK_GROUP_OWNER_ID=${VK_GROUP_OWNER_ID}
      - VK_MAIN_ALBUM_ID=${VK_MAIN_ALBUM_ID}
      - VK_CLIENT_ID=${VK_CLIENT_ID}
      - VK_CLIENT_SECRET=${VK_CLIENT_SECRET}
      - VK_AUTHORIZATION_CALLBACK=${VK_AUTHORIZATION_CALLBACK}
    ports:
      - "3000:3000"
    container_name: "nuxt-build"

  cron:
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    command: "crond -f -d 8"
    links:
      - webapp
    volumes:
        - './docker/cron/cron:/etc/crontabs/root:z'
    container_name: "cron"
#      restart: unless-stopped
