version: "3.9"
services:
  webapp:
    build:
      context: .
    command: "yarn start -H 0.0.0.0"
    volumes:
      - build-node_modules:/build/node_modules
    ports:
      - "3000:3000"
    container_name: "nuxt-build"

volumes:
  build-node_modules:
    external: true
