POST https://pu.vk.com/c537232/upload_doc.php?act=add_doc&mid=99949353&aid=0&gid=203255283&type=0&hash=8628a4171044305f0aab7d60c57428e5&rhash=b1b8447bcd234ad67d15c033546e0647&api=1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="message.txt"

< ./message.txt
--WebAppBoundary--


GET http://localhost:3000/api/queuePost
Content-Type: application/json

{
  "news": "test",
  "topic": "test post",
  "postOnDate": "2021-03-18_17:42"
}

###

GET http://localhost:3000/action/processQueue
Content-Type: application/json

###

GET http://localhost:3000/api/hello
Content-Type: application/json

###

GET https://vkpostqueue-nuxt-mll03haie-lynx-r.vercel.app/action/processQueue
Content-Type: application/json

###

GET http://localhost:3000/api/touch-cron
Content-Type: application/json


