###

GET http://localhost:3000/api/queueNews
Content-Type: application/json

{
  "news": "test",
  "topic": "test post",
  "postOnDate": "2021-03-18_17:42"
}

###

GET http://localhost:3000/action/processQueue
Content-Type: application/json

###

GET http://localhost:3000/api/hello
Content-Type: application/json

###

GET https://vkpostqueue-nuxt-mll03haie-lynx-r.vercel.app/action/processQueue
Content-Type: application/json

###

GET http://localhost:3000/api/generatePresignedUrl
Content-Type: application/json


